# Generated by Django 2.1.5 on 2019-01-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0008_caregiver_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='relationship_with_child',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
