# Generated by Django 2.1.5 on 2019-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0009_caregiver_relationship_with_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='day_of_birth',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
