# Generated by Django 2.1.5 on 2019-01-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0011_auto_20190108_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ManyToManyField(to='NurseryApp.Child')),
                ('group', models.ManyToManyField(to='NurseryApp.Group')),
            ],
        ),
    ]
