# Generated by Django 2.1.5 on 2019-01-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0012_waiting_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='child',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='NurseryApp.Activity'),
        ),
        migrations.AlterField(
            model_name='child',
            name='diet',
            field=models.ManyToManyField(blank=True, null=True, to='NurseryApp.Diet'),
        ),
    ]
