# Generated by Django 2.1.5 on 2019-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0013_auto_20190109_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='activity',
            field=models.ManyToManyField(blank=True, to='NurseryApp.Activity'),
        ),
        migrations.AlterField(
            model_name='child',
            name='diet',
            field=models.ManyToManyField(blank=True, to='NurseryApp.Diet'),
        ),
    ]
