# Generated by Django 2.1.5 on 2019-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0015_child_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('1', 'Verification'), ('2', 'Waiting'), ('3', 'Accepted')], default='1', max_length=1),
        ),
    ]
