# Generated by Django 2.1.5 on 2019-01-09 22:53e"

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0016_child_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting_list',
            name='group',
            field=models.ManyToManyField(blank=True, to='NurseryApp.Group'),
        ),
    ]
