# Generated by Django 2.1.5 on 2019-01-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0017_auto_20190109_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiting_list',
            name='child',
        ),
        migrations.RemoveField(
            model_name='waiting_list',
            name='group',
        ),
        migrations.DeleteModel(
            name='Waiting_list',
        ),
    ]
