# Generated by Django 2.1.5 on 2019-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0019_group_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
