# Generated by Django 2.1.5 on 2019-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0020_parent_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
