# Generated by Django 2.1.5 on 2019-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0021_child_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
