# Generated by Django 2.1.5 on 2019-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0022_child_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('1', 'M'), ('2', 'F')], max_length=1),
        ),
    ]
