# Generated by Django 2.1.5 on 2019-01-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryApp', '0023_auto_20190111_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryApp.Parent')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryApp.Teacher')),
            ],
        ),
    ]
